spring:
  application:
    name: normal-thread
  threads:
    virtual:
      enabled: false
  cloud:
    openfeign:
      httpclient:
        enabled: true
        hc5:
          enabled: true
        max-connections: 1000      # Padrão é baixo (ex: 200)
        max-connections-per-route: 500 # Padrão é baixíssimo (ex: 50)


env:
  url-a: ${SERVICE_A_URL:http://localhost:9010}
  url-b: ${SERVICE_B_URL:http://test:8080}
  url-c: ${SERVICE_C_URL:http://test:8080}

feign:
  httpclient:
    enabled: true
    hc5:
      enabled: true
    max-connections: 1000      # Padrão é baixo (ex: 200)
    max-connections-per-route: 500 # Padrão é baixíssimo (ex: 50)
  okhttp:
    enabled: true