spring:
  application:
    name: normal-thread
  threads:
    virtual:
      enabled: false


env:
  url-a: ${SERVICE_A_URL:http://localhost:9010}
  url-b: ${SERVICE_B_URL:http://test:8080}
  url-c: ${SERVICE_C_URL:http://test:8080}

feign:
  httpclient:
    max-connections: 200
    max-connections-per-route: 50
  okhttp:
    enabled: true